{{- if eq .Values.version "v1alpha2" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cabpk-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabpk-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
{{- end }}
